### ISSUE TITLE
A error when make SLICO

### ISSUE THREAD

**Issue by shammmmmless** [411-3/PSP-CRF#1]
I meet a error when I make SLICO as following:

/home/test/Cworkspace/PSP-CRF/src/SLICO/example/j2seg.cpp: In function ‘int main(int, char**)’:
/home/test/Cworkspace/PSP-CRF/src/SLICO/example/j2seg.cpp:55:37: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
  readbmp("1.bmp", image_buffer, h, w);
                                     ^
/home/test/Cworkspace/PSP-CRF/src/SLICO/example/j2seg.cpp:260:110: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
 /LiHuan/SLICO/example/result/temp_seg.jpg", image_buffer, w, h, JPEG_QUALITY);
                                                                             ^
make[2]: *** No rule to make target '/home/xduser/LiHuan/SLICO/lib/libjpeg.a', needed by 'example/j2seg'.  Stop.
CMakeFiles/Makefile2:158: recipe for target 'example/CMakeFiles/j2seg.dir/all' failed
make[1]: *** [example/CMakeFiles/j2seg.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How can I fix it? what the version of opencv you use in this project?

**Comment by shammmmmless** [comment]
I just make the psp_crf by your libSLIC.a successfully, but how can I get a score map as a npy file? Could you provide some data for test?

**Comment by 411-3** [comment]
Hi ! 
This work was completed during my postgraduate study, so my test data is on our lab's workstation. I got the score map by running the FCN net with caffe at that time. By running FCN, we will get a score map of every pixel of the image,  and the original method was to get maximum score of pixel. We can save the score map and use CRF to optimize the score. Thanks.
